// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommonsitvisors.proxies;

public class DropDataItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dropDataItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NanoflowCommonsITvisors.DropDataItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		seqNbr("seqNbr"),
		itemId("itemId");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DropDataItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NanoflowCommonsITvisors.DropDataItem"));
	}

	protected DropDataItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dropDataItemMendixObject)
	{
		if (dropDataItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NanoflowCommonsITvisors.DropDataItem", dropDataItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NanoflowCommonsITvisors.DropDataItem");

		this.dropDataItemMendixObject = dropDataItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DropDataItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nanoflowcommonsitvisors.proxies.DropDataItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nanoflowcommonsitvisors.proxies.DropDataItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nanoflowcommonsitvisors.proxies.DropDataItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nanoflowcommonsitvisors.proxies.DropDataItem(context, mendixObject);
	}

	public static nanoflowcommonsitvisors.proxies.DropDataItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nanoflowcommonsitvisors.proxies.DropDataItem.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of seqNbr
	 */
	public final java.lang.Integer getseqNbr()
	{
		return getseqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of seqNbr
	 */
	public final java.lang.Integer getseqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.seqNbr.toString());
	}

	/**
	 * Set value of seqNbr
	 * @param seqnbr
	 */
	public final void setseqNbr(java.lang.Integer seqnbr)
	{
		setseqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of seqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setseqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.seqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of itemId
	 */
	public final java.lang.String getitemId()
	{
		return getitemId(getContext());
	}

	/**
	 * @param context
	 * @return value of itemId
	 */
	public final java.lang.String getitemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.itemId.toString());
	}

	/**
	 * Set value of itemId
	 * @param itemid
	 */
	public final void setitemId(java.lang.String itemid)
	{
		setitemId(getContext(), itemid);
	}

	/**
	 * Set value of itemId
	 * @param context
	 * @param itemid
	 */
	public final void setitemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itemid)
	{
		getMendixObject().setValue(context, MemberNames.itemId.toString(), itemid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dropDataItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nanoflowcommonsitvisors.proxies.DropDataItem that = (nanoflowcommonsitvisors.proxies.DropDataItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NanoflowCommonsITvisors.DropDataItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
