// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommonsitvisors.proxies;

public enum GetOfflineOperator
{
	equals(new java.lang.String[][] { new java.lang.String[] { "en_US", "Equals" } }),
	lessThan(new java.lang.String[][] { new java.lang.String[] { "en_US", "Less than" } }),
	lessThanOrEquals(new java.lang.String[][] { new java.lang.String[] { "en_US", "Less than or equals" } }),
	greaterThan(new java.lang.String[][] { new java.lang.String[] { "en_US", "Greater than" } }),
	greaterThanOrEquals(new java.lang.String[][] { new java.lang.String[] { "en_US", "Greater than or equals" } }),
	contains(new java.lang.String[][] { new java.lang.String[] { "en_US", "Contains" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private GetOfflineOperator(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
