// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Cordova Keyboard plugin. https://www.npmjs.com/package/cordova-plugin-keyboard
 * 
 * Specifies whether content of page would be automatically scrolled to the top of the page when keyboard is hiding.
 * 
 * Note that not the mendix page container but the viewport gets scrolled back into position. Any scroll position within the Mendix layout is left as is.
 * @param {boolean} newValue
 * @returns {Promise.<boolean>}
 */
export async function Keyboard_SetAutomaticScrollToTopOnHiding(newValue) {
	// BEGIN USER CODE
	return new Promise(function(resolve, reject) {
		if (typeof Keyboard !== "undefined") {
			Keyboard.automaticScrollToTopOnHiding = newValue;
			resolve(true);
		} else {
			reject(Error("Keyboard plugin not available."));
		}
	});
	// END USER CODE
}
