// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the NativeMobile module
	public static void aCT_Record_Download(IContext context, nativemobile.proxies.Record _record)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Record", _record == null ? null : _record.getMendixObject());
		Core.microflowCall("NativeMobile.ACT_Record_Download").withParams(params).execute(context);
	}
}